gpu_devices: [0]
backbone_layers:
- 2
- 3
- 7
betas:
- 0.9
- 0.999
batchsize: 64
checkpoint: checkpoints/weights.pth
data: dataset/data/train.pkl
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
dim: 256
epochs: 10
gamma: 0.9995
id: null
load_chkpt: checkpoints/weights.pth
lr: 0.001
max_height: 192
max_seq_len: 512
max_width: 672
micro_batchsize: -1
min_height: 32
min_width: 32
model_path: checkpoints
name: i2l
num_tokens: 8000
output_path: outputs
pad: false
patch_size: 16
sample_freq: 3000
save_freq: 5
seed: 42
temperature: 0.2
test_samples: 5
testbatchsize: 20
tokenizer: dataset/tokenizer.json
valbatches: 100
valdata: dataset/data/val.pkl
